### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by tomyDevelop** [tomyDevelop/favorite_scenes#50]
## 各種情報
- サービス名: FavoriteScenes
- サービスURL: https://favoritescenes-2f29520d09dd.herokuapp.com/
- サービス概要：
  - YouTube動画で人に共有したいシーンや見返したいシーンを登録し、共有できるサービスです。
  - 投稿者は、フォームでYouTube動画とシーンをシーンコレクションとして登録します。その際にYouTube動画全体の見どころや、シーンごとの見どころを登録できます。
  - 閲覧者はアカウント登録不要で、投稿者が投稿したシーンコレクションを閲覧し、コメントできます。
- サービスを考えた経緯：よくゲーム配信を見るのですが、ゲーム配信はかなり長時間（短くても2時間くらいはある）で自分の気に入ったシーンをあとで見返したり共有したりすることが難しいので、それらが簡単にできるサービスを作りました。

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- MVPリリース時
  - [x] ユーザー登録機能
  - [x] ログイン機能
  - [ ] パスワード変更機能
  - [ ] メールアドレス変更機能
  - [x] コンテンツ一覧表示機能
  - [x] コンテンツ投稿機能
  - [ ] タグ機能
  - [x] コンテンツ投稿ガイド機能（ツールチップで誘導するイメージ）
  - [x] コンテンツ閲覧機能（未ログインでも閲覧可能）
  - [x] コンテンツ編集機能
  - [x] コンテンツ削除機能
  - [x] コンテンツ検索機能（ワード検索）
  - [ ] いいね機能
  - [ ] いいね解除機能

## READMEレビュー時から変更した機能
- チェックできていない機能は、4/16の見積もり面談で冨田講師と相談しMVP時点では実装しないこととしました。（メイン機能だけをまず実装する）

## サービスイメージがわかるようなスクリーンショット等
- シーンコレクション登録画面イメージ
[![Image from Gyazo](https://i.gyazo.com/dd3b02dcf520b2147ac132dc1d6c4d24.png)](https://gyazo.com/dd3b02dcf520b2147ac132dc1d6c4d24)
- シーン登録イメージ
[![Image from Gyazo](https://i.gyazo.com/50f0b9977b94d5f7862c101f533a168f.png)](https://gyazo.com/50f0b9977b94d5f7862c101f533a168f)
- 閲覧画面イメージ
[![Image from Gyazo](https://i.gyazo.com/2fd9d973c71fcaf5a624ab90122b8424.png)](https://gyazo.com/2fd9d973c71fcaf5a624ab90122b8424)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
